# Web服务配置
server:
  port: 8080
# MySQL数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 101807
    url: jdbc:mysql://172.19.43.20:3306/m_mail?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true

# Redis配置
  data:
    redis:
      host: 172.19.43.20
      port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# Mybatis-Plus的配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      update-strategy: not_empty
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# Swagger配置
springdoc:
  swagger-ui:
    path: /doc.html
    tags-sorter: alpha
    operations-sorter: order
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      display-name: 'M-Mail'
      paths-to-match: '/**'
      packages-to-scan: com.pandaer.project
  default-flat-param-object: true

project:
  user:
    upload-dir: "D:/images"
  auth:
    jwt:
      secret: KzeVaY8LkiUi6IMnKTvBrGxZDJ51Vh3Z